= API
:sectnums:
ifndef::toc:[:toc: left]
ifndef::toplevels:[:toclevels: 2]
ifndef::stem[:stem: latexmath]
ifndef::icons[:icons: font]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: tomorrow-night]

++++
<style type="text/css">
th,td {
    border: solid 0px;  
}　
p>code {background-color: #aaaaaa};
td>code {background-color: #aaaaaa};
</style>
++++

== T( __timeFunction__ )

[source,js]
----
const timeFunction = (self) ⇒ { /*…​*/ self.now = value;};

const timeline = T( timeFunction );
----

`timefunction` is a function to be called on *Initialization of the `timeline`* +
`timeline` can be defined with `timefuncton` that can be empty

== __timeline__.now

[source,js]
----
const timeFunction = (self) ⇒ { /*…​*/ self.now = value;};
----

== .sync( __someFunction__ )

[source,js]
----
const timeline1 = timeline
                         .sync( someFunction );
----

`timeline1` is anonther _timeline_ that depends on `timeline` sychronized with `someFunction`

 
== TypeScript type definition

https://github.com/stken2050/timeline-monad/blob/master/dist/esm/timeline-monad.d.ts[timeline-monad TypeScript type definition]

[source,js]
.timeline type definition
----
interface timeline {
    type: string;
    now: any;
    next: any;
    sync: Function;
    "->": Function;
}
declare const T: (initFunction?: Function) => timeline;
export { T };
----



[TIP]
.**timeline-monad** is extremely simple and easy to learn.
====
`T`, `now`, `sync` (`"->"`)  are the only reserved words and elements provided by the module. 


`T` is a function to return a new  __timeline__ object.
====

